[build]
  base = "apps/web"
  command = "cd ../.. && pnpm install && pnpm build --filter=web"
  publish = ".next"
  ignore = "git log -1 --pretty=%an | grep -q 'dependabot'"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING = "1"
  TURBO_TELEMETRY_DISABLED = "1"

[context.production]
  command = "cd ../.. && pnpm install && pnpm build --filter=web"

[context.deploy-preview]
  command = "cd ../.. && pnpm install && pnpm build --filter=web"
