/**
 * Catalog Route — Product Search
 *
 * Searches the product catalog via the Python bridge (Browser-Use / Purch)
 * or falls back to a direct Venice AI search.
 *
 * Architecture note (ADR 0001):
 *   Catalog lives on Hetzner because it requires long-running bridge calls.
 *   Vercel rewrites /api/agent/catalog → Hetzner via next.config.js.
 */

const express = require('express');
const router = express.Router();
const logger = require('../lib/logger');
const { searchViaBridge, searchViaVenice } = require('../lib/product-search');

// GET /api/agent/catalog?query=...&limit=10
router.get('/', async (req, res) => {
  try {
    const query = req.query.query;
    const limit = parseInt(req.query.limit) || 10;
    const refresh = req.query.refresh === 'true';

    if (!query || query.length < 2) {
      return res.status(400).json({ error: 'Query parameter required (min 2 chars)' });
    }

    // Try bridge first, fall back to Venice
    let result = refresh ? null : await searchViaBridge(query, limit);
    let source = 'bridge';

    if (!result) {
      result = await searchViaVenice(query, limit);
      source = 'venice-ai';
    }

    if (!result) {
      return res.status(503).json({ error: 'All search backends unavailable' });
    }

    const synthetic = source === 'venice-ai';

    res.json({
      query,
      count: result.items.length,
      source,
      synthetic, // true when generated by AI (not real catalog data)
      cached: !refresh && source === 'bridge',
      items: result.items,
      marketSignals: result.signals || [],
    });
  } catch (error) {
    logger.error('Catalog search error', { component: 'catalog' }, error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/agent/catalog (advanced search with auth)
router.post('/', async (req, res) => {
  try {
    const { query, limit = 10, forceRefresh = false } = req.body;

    if (!query || query.length < 2) {
      return res.status(400).json({ error: 'Query required (min 2 chars)' });
    }

    let result = forceRefresh ? null : await searchViaBridge(query, limit);
    let source = 'bridge';

    if (!result) {
      result = await searchViaVenice(query, limit);
      source = 'venice-ai';
    }

    if (!result) {
      return res.status(503).json({ error: 'All search backends unavailable' });
    }

    const synthetic = source === 'venice-ai';

    res.json({
      query,
      count: result.items.length,
      source,
      synthetic, // true when generated by AI (not real catalog data)
      cached: !forceRefresh && source === 'bridge',
      items: result.items,
      marketSignals: result.signals || [],
    });
  } catch (error) {
    logger.error('Catalog POST error', { component: 'catalog' }, error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

module.exports = router;
