/**
 * Catalog Route — Product Search
 *
 * Searches the product catalog via the Python bridge (Browser-Use / Purch)
 * or falls back to a direct Venice AI search.
 *
 * Architecture note (ADR 0001):
 *   Catalog lives on Hetzner because it requires long-running bridge calls.
 *   Vercel rewrites /api/agent/catalog → Hetzner via next.config.js.
 */

const express = require('express');
const router = express.Router();
const logger = require('../lib/logger');

const BRIDGE_URL = process.env.BRIDGE_URL || 'http://localhost:48752';
const VERCEL_DOMAIN = process.env.VERCEL_DOMAIN || '';

/**
 * Proxy search request to the Python bridge
 */
async function searchViaBridge(query, limit) {
  if (!BRIDGE_URL) return null;

  try {
    const response = await fetch(`${BRIDGE_URL}/v1/agent/search`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, max_results: limit }),
      signal: AbortSignal.timeout(15000),
    });

    if (!response.ok) {
      logger.warn('Bridge search returned non-OK', {
        component: 'catalog',
        status: response.status,
      });
      return null;
    }

    return await response.json();
  } catch (err) {
    logger.warn('Bridge search failed, falling back', {
      component: 'catalog',
      error: err.message,
    });
    return null;
  }
}

/**
 * Fallback: use Venice AI to generate catalog-style suggestions
 */
async function searchViaVenice(query, limit) {
  const veniceKey = process.env.VENICE_API_KEY;
  if (!veniceKey) return null;

  try {
    const response = await fetch('https://api.venice.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${veniceKey}`,
      },
      body: JSON.stringify({
        model: 'qwen3-vl-235b-a22b',
        messages: [
          {
            role: 'user',
            content: `You are a fashion product catalog. Given the query "${query}", return a JSON array of ${limit} fashion item suggestions. Each item must have: name, brand, category, price (number), description. Return ONLY valid JSON, no markdown.`,
          },
        ],
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!response.ok) return null;

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content || '[]';
    // Strip markdown code fences if present
    const cleaned = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    const items = JSON.parse(cleaned);
    return { items: Array.isArray(items) ? items.slice(0, limit) : [] };
  } catch (err) {
    logger.warn('Venice catalog search failed', {
      component: 'catalog',
      error: err.message,
    });
    return null;
  }
}

// GET /api/agent/catalog?query=...&limit=10
router.get('/', async (req, res) => {
  try {
    const query = req.query.query;
    const limit = parseInt(req.query.limit) || 10;
    const refresh = req.query.refresh === 'true';

    if (!query || query.length < 2) {
      return res.status(400).json({ error: 'Query parameter required (min 2 chars)' });
    }

    // Try bridge first, fall back to Venice
    let result = refresh ? null : await searchViaBridge(query, limit);
    let source = 'bridge';

    if (!result) {
      result = await searchViaVenice(query, limit);
      source = 'venice-ai';
    }

    if (!result) {
      return res.status(503).json({ error: 'All search backends unavailable' });
    }

    const synthetic = source === 'venice-ai';

    res.json({
      query,
      count: result.items.length,
      source,
      synthetic, // true when generated by AI (not real catalog data)
      cached: !refresh && source === 'bridge',
      items: result.items,
    });
  } catch (error) {
    logger.error('Catalog search error', { component: 'catalog' }, error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// POST /api/agent/catalog (advanced search with auth)
router.post('/', async (req, res) => {
  try {
    const { query, limit = 10, forceRefresh = false } = req.body;

    if (!query || query.length < 2) {
      return res.status(400).json({ error: 'Query required (min 2 chars)' });
    }

    let result = forceRefresh ? null : await searchViaBridge(query, limit);
    let source = 'bridge';

    if (!result) {
      result = await searchViaVenice(query, limit);
      source = 'venice-ai';
    }

    if (!result) {
      return res.status(503).json({ error: 'All search backends unavailable' });
    }

    const synthetic = source === 'venice-ai';

    res.json({
      query,
      count: result.items.length,
      source,
      synthetic, // true when generated by AI (not real catalog data)
      cached: !forceRefresh && source === 'bridge',
      items: result.items,
    });
  } catch (error) {
    logger.error('Catalog POST error', { component: 'catalog' }, error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

module.exports = router;
