import React, { useState } from 'react';
import { Button } from '@repo/ui/button';
import { useAccount, useWalletClient, usePublicClient, useChainId } from 'wagmi';
import { ImageIcon, Sparkles, CheckCircle2, ArrowRight } from 'lucide-react';
import { mintNFTWithSplit, createSplitsClient } from '@repo/blockchain-client';
import { celo, celoAlfajores } from '../../config/chains';
import { Address } from 'viem';

interface MintLookButtonProps {
  imageUrl: string; 
  ipfsCid: string;
  aiCritique: string;
  onUpload: () => Promise<{ url: string; ipfsUrl: string; ipfsCid: string }>;
}

export function MintLookButton({ imageUrl, ipfsCid, aiCritique, onUpload }: MintLookButtonProps) {
  const { address, isConnected } = useAccount();
  const { data: walletClient } = useWalletClient();
  const publicClient = usePublicClient();
  const chainId = useChainId();
  const [isMinting, setIsMinting] = useState(false);
  const [mintedTokenId, setMintedTokenId] = useState<string | null>(null);

  const handleMint = async () => {
    if (!isConnected || !walletClient || !publicClient || !address) {
      alert('Please connect your wallet first');
      return;
    }

    try {
      setIsMinting(true);

      // 1. Ensure image is uploaded
      let currentCid = ipfsCid;
      if (!currentCid) {
        const data = await onUpload();
        currentCid = data.ipfsCid;
      }

      // 2. Prepare Metadata
      const metadata = {
        name: `Style Critique by AI Stylist`,
        description: `A unique fashion analysis generated by the OnPoint AI Stylist.\n\nCritique: ${aiCritique}`,
        image: `ipfs://${currentCid}`,
        external_url: 'https://onpoint.fashion',
        attributes: [
          { trait_type: 'Stylist Mode', value: 'Live AR' },
          { trait_type: 'Confidence Score', value: 'High' }
        ]
      };

      // 3. Upload Metadata to IPFS via API
      const uploadRes = await fetch('/api/ipfs/upload', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ data: JSON.stringify(metadata), name: 'metadata.json' })
      });

      if (!uploadRes.ok) throw new Error('Metadata upload failed');
      const { uri: metadataUri } = await uploadRes.json();
      console.log('Metadata uploaded:', metadataUri);

      // 4. Setup Splits (85% user, 15% platform)
      const splitsClient = createSplitsClient(chainId, publicClient, walletClient);
      const splitParams = {
        recipients: [
          { address: address as Address, percentAllocation: 85.0 },
          { address: '0x05f012C12123D69E8324A251ae7D15A92C4549c1' as Address, percentAllocation: 15.0 }, // Platform fee wallet
        ]
      };

      // 5. Get Contract Address
      const currentChain = chainId === celoAlfajores.id ? celoAlfajores : celo;
      const contractAddress = (currentChain.contracts as any).OnPointNFT.address;

      // 6. Execute Mint
      const result = await mintNFTWithSplit(
        walletClient,
        publicClient,
        contractAddress,
        metadataUri,
        splitParams,
        splitsClient
      );

      if (result.status === 'confirmed') {
        setMintedTokenId(result.tokenId);
      } else {
        throw new Error('Transaction failed');
      }

    } catch (err) {
      console.error('Minting failed:', err);
      alert('Minting failed. Please make sure you are on Celo and have enough gas.');
    } finally {
      setIsMinting(false);
    }
  };

  if (mintedTokenId) {
    const currentChain = chainId === celoAlfajores.id ? celoAlfajores : celo;
    const explorerUrl = currentChain.blockExplorers.default.url;
    const contractAddress = (currentChain.contracts as any).OnPointNFT.address;

    return (
      <Button 
        className="w-full bg-green-500/20 hover:bg-green-500/30 text-green-400 border border-green-500/30 rounded-full py-6 text-sm font-bold gap-2"
        onClick={() => window.open(`${explorerUrl}/token/${contractAddress}?a=${mintedTokenId}`, '_blank')}
      >
        <CheckCircle2 className="w-5 h-5 text-green-500" />
        Minted NFT #{mintedTokenId}
        <ArrowRight className="w-4 h-4 ml-auto opacity-50" />
      </Button>
    );
  }

  return (
    <Button 
      className="w-full bg-indigo-600 hover:bg-indigo-500 text-white rounded-full py-6 text-lg font-bold gap-2 shadow-lg shadow-indigo-500/20"
      disabled={isMinting}
      onClick={handleMint}
    >
      {isMinting ? <Sparkles className="animate-spin w-6 h-6" /> : <ImageIcon className="w-6 h-6 text-white/80" />}
      {isMinting ? 'Minting on Celo...' : 'Mint as NFT (85% Royalty)'}
    </Button>
  );
}
