import React, { useState, useCallback } from "react";
import { Button } from "@repo/ui/button";
import {
  useAccount,
  useChainId,
  useWriteContract,
  useWaitForTransactionReceipt,
} from "wagmi";
import {
  ImageIcon,
  Sparkles,
  CheckCircle2,
  ArrowRight,
  AlertCircle,
  X,
  Loader2,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { celo, celoSepolia } from "../../config/chains";
import { type Address } from "viem";

interface MintLookButtonProps {
  imageUrl: string;
  ipfsCid: string;
  aiCritique: string;
  onUpload: () => Promise<{ url: string; ipfsUrl: string; ipfsCid: string }>;
}

/**
 * Minimal NFT mint ABI (assumes ERC-721 with mint(to, tokenURI)).
 * Adjust if your contract uses a different signature.
 */
const NFT_MINT_ABI = [
  {
    name: "mint",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "to", type: "address" },
      { name: "uri", type: "string" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

interface MintError {
  title: string;
  message: string;
  hint?: string;
}

/**
 * MintLookButton — Mint a Proof of Style NFT on Celo.
 *
 * Flow:
 * 1. Upload image to IPFS (via onUpload callback)
 * 2. Build metadata JSON, upload metadata to IPFS
 * 3. Call mint() on the NFT contract via wagmi (user signs in wallet)
 *
 * Errors shown inline — no raw alert().
 */
export function MintLookButton({
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  imageUrl,
  ipfsCid,
  aiCritique,
  onUpload,
}: MintLookButtonProps) {
  const { address, isConnected } = useAccount();
  const chainId = useChainId();
  const [isMinting, setIsMinting] = useState(false);
  const [mintedTokenId, setMintedTokenId] = useState<string | null>(null);
  const [mintError, setMintError] = useState<MintError | null>(null);

  const {
    writeContract,
    isPending: isWritePending,
    data: txHash,
    error: writeError,
    reset: resetWrite,
  } = useWriteContract();

  const { isSuccess: isConfirmed } = useWaitForTransactionReceipt({
    hash: txHash,
  });

  // When on-chain tx confirms, extract token ID from logs
  React.useEffect(() => {
    if (isConfirmed && txHash) {
      // For simplicity, show success with tx hash.
      // In production you'd parse the Transfer event for the tokenId.
      setMintedTokenId(txHash.slice(2, 10)); // short hash as placeholder
      setIsMinting(false);
    }
  }, [isConfirmed, txHash]);

  // When writeContract fails
  React.useEffect(() => {
    if (writeError) {
      const msg = writeError.message || "";
      if (msg.includes("User rejected")) {
        setMintError({
          title: "Transaction Cancelled",
          message: "You rejected the transaction in your wallet.",
        });
      } else {
        setMintError({
          title: "Minting Failed",
          message:
            "The transaction could not be completed. Make sure you are on Celo and have enough CELO for gas.",
          hint: msg.slice(0, 200),
        });
      }
      setIsMinting(false);
    }
  }, [writeError]);

  const handleMint = useCallback(async () => {
    if (!isConnected || !address) {
      setMintError({
        title: "Wallet Not Connected",
        message: "Please connect your wallet first to mint.",
      });
      return;
    }

    setMintError(null);
    setIsMinting(true);
    resetWrite();

    try {
      // 1. Ensure image is uploaded
      let currentCid = ipfsCid;
      if (!currentCid) {
        const data = await onUpload();
        currentCid = data.ipfsCid;
      }

      // 2. Prepare metadata
      const metadata = {
        name: "Style Critique by AI Stylist",
        description: `A unique fashion analysis generated by the OnPoint AI Stylist.\n\nCritique: ${aiCritique}`,
        image: `ipfs://${currentCid}`,
        external_url: "https://onpoint.fashion",
        attributes: [
          { trait_type: "Stylist Mode", value: "Live AR" },
          { trait_type: "Confidence Score", value: "High" },
        ],
      };

      // 3. Upload metadata to IPFS
      const uploadRes = await fetch("/api/ipfs/upload", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          data: JSON.stringify(metadata),
          name: "metadata.json",
        }),
      });

      if (!uploadRes.ok) {
        const errBody = await uploadRes.text();
        throw new Error(`Metadata upload failed: ${errBody}`);
      }

      const { uri: metadataUri } = await uploadRes.json();

      // 4. Get contract address
      const currentChain = chainId === celoSepolia.id ? celoSepolia : celo;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const contractAddress = (currentChain.contracts as any).OnPointNFT
        ?.address;

      if (!contractAddress) {
        throw new Error(
          "NFT contract not configured for this chain. Switch to Celo.",
        );
      }

      // 5. Write on-chain — user signs in their wallet
      writeContract({
        address: contractAddress as Address,
        abi: NFT_MINT_ABI,
        functionName: "mint",
        args: [address, metadataUri],
        chainId: currentChain.id,
      });
    } catch (err: unknown) {
      console.error("Minting failed:", err);
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("Metadata upload failed")) {
        setMintError({
          title: "Upload Failed",
          message:
            "Could not upload your style metadata to IPFS. Please try again.",
          hint: msg,
        });
      } else if (msg.includes("not configured")) {
        setMintError({
          title: "Wrong Network",
          message: msg,
          hint: "Switch to Celo or Celo Sepolia to mint.",
        });
      } else {
        setMintError({
          title: "Minting Failed",
          message:
            "Something went wrong. Make sure you are on Celo and have enough CELO for gas.",
          hint: msg,
        });
      }
      setIsMinting(false);
    }
  }, [
    isConnected,
    address,
    ipfsCid,
    aiCritique,
    onUpload,
    chainId,
    writeContract,
    resetWrite,
  ]);

  // ── Success state ──
  if (mintedTokenId) {
    const currentChain = chainId === celoSepolia.id ? celoSepolia : celo;
    const explorerUrl = currentChain.blockExplorers.default.url;

    return (
      <Button
        className="w-full bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-400 border border-emerald-500/30 rounded-full py-6 text-sm font-bold gap-2"
        onClick={() => window.open(`${explorerUrl}/tx/${txHash}`, "_blank")}
      >
        <CheckCircle2 className="w-5 h-5 text-emerald-500" />
        Minted on Celo
        <ArrowRight className="w-4 h-4 ml-auto opacity-50" />
      </Button>
    );
  }

  return (
    <div className="space-y-2">
      {/* Styled error display */}
      <AnimatePresence>
        {mintError && (
          <motion.div
            initial={{ opacity: 0, y: -8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            className="bg-rose-500/10 border border-rose-500/30 rounded-2xl p-4 flex gap-3"
          >
            <div className="w-8 h-8 rounded-xl bg-rose-500/20 flex items-center justify-center shrink-0 mt-0.5">
              <AlertCircle className="w-4 h-4 text-rose-400" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-white font-bold text-sm">{mintError.title}</p>
              <p className="text-slate-400 text-xs mt-0.5">
                {mintError.message}
              </p>
              {mintError.hint && (
                <p className="text-slate-500 text-[10px] mt-1 font-mono truncate">
                  {mintError.hint}
                </p>
              )}
            </div>
            <button
              onClick={() => setMintError(null)}
              className="p-1 hover:bg-white/10 rounded-full shrink-0 self-start"
            >
              <X className="w-4 h-4 text-slate-500" />
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Processing state */}
      {(isMinting || isWritePending) && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="bg-indigo-500/10 border border-indigo-500/20 rounded-2xl p-4 flex items-center gap-3"
        >
          <Loader2 className="w-5 h-5 text-indigo-400 animate-spin shrink-0" />
          <div>
            <p className="text-white font-medium text-sm">
              {isWritePending
                ? "Confirm in your wallet…"
                : "Preparing your Proof of Style…"}
            </p>
            <p className="text-slate-400 text-[10px]">
              Uploading metadata, then minting on Celo
            </p>
          </div>
        </motion.div>
      )}

      {/* Mint button */}
      <Button
        className="w-full bg-indigo-600 hover:bg-indigo-500 text-white rounded-full py-6 text-lg font-bold gap-2 shadow-lg shadow-indigo-500/20"
        disabled={isMinting || isWritePending}
        onClick={handleMint}
      >
        {isMinting || isWritePending ? (
          <Sparkles className="animate-spin w-6 h-6" />
        ) : (
          <ImageIcon className="w-6 h-6 text-white/80" />
        )}
        {isMinting || isWritePending
          ? "Minting on Celo…"
          : "Mint as NFT (85% Royalty)"}
      </Button>
    </div>
  );
}
