import {
  pgTable,
  uuid,
  text,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";
import { curators } from "./curators";
import { kitSkus } from "./kit-skus";

/**
 * Listings — a Curator's inventory item.
 *
 * Physical listings reference a KitSKU and have sizes/stock.
 * Digital listings (AI-generated garments) have no KitSKU — the
 * "garment image" is a generated design stored in R2. Digital listings
 * are try-on only (no order endpoint); they funnel agents to similar
 * physical items from human curators.
 *
 * Created when Wanja texts "+ arsenal home M 2500 4" + photo, or
 * generated by the platform for an AI digital curator.
 * Photo references are R2 keys (never URLs).
 */
export const listings = pgTable("listings", {
  id: uuid("id").primaryKey().defaultRandom(),

  curatorSlug: text("curator_slug")
    .notNull()
    .references(() => curators.slug, { onDelete: "cascade" }),

  // Nullable for digital listings — AI-generated garments don't map to a KitSKU
  skuId: text("sku_id").references(() => kitSkus.id),

  // "physical" (default) or "digital". Digital listings have no stock/size
  // constraints and are excluded from the order endpoint.
  inventoryType: text("inventory_type", {
    enum: ["physical", "digital"],
  })
    .notNull()
    .default("physical"),

  // [{size: "M", stock: 4, price: 2500}] — empty for digital listings
  sizes: jsonb("sizes").notNull().default("[]"),

  // R2 keys for Curator's own photos (override official kit image)
  // For digital listings, this is the AI-generated garment design
  photoKeys: text("photo_keys").array().notNull().default([]),

  // Human-readable title for digital listings (physical listings derive
  // their title from the KitSKU join). Also used as the generation prompt
  // seed for digital garments.
  title: text("title"),

  // Style/vertical tags for matching digital → physical (e.g. ["football", "arsenal", "home"])
  tags: text("tags").array().notNull().default([]),

  status: text("status", {
    enum: ["live", "paused", "archived"],
  })
    .notNull()
    .default("live"),

  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});
