import Link from "next/link";
import type { Metadata } from "next";
import { Palette, FileText } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | BeOnPoint",
  description:
    "BeOnPoint Terms of Service — the rules and conditions for using our AI styling and curator storefront platform.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground selection:bg-primary/30">
      <header className="sticky top-0 z-50 w-full border-b border-border/60 bg-background/95 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-3xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2 text-sm font-bold">
            <div className="rounded-lg bg-gradient-to-br from-primary to-accent p-1.5 shadow-md">
              <Palette className="h-4 w-4 text-white" />
            </div>
            BeOnPoint
          </Link>
          <Link
            href="/privacy"
            className="text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-4 py-12">
        <div className="mb-8 flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
            <FileText className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-black tracking-tight">Terms of Service</h1>
            <p className="text-sm text-muted-foreground">Last updated: June 2026</p>
          </div>
        </div>

        <div className="space-y-8 text-sm leading-7 text-muted-foreground">
          <section>
            <h2 className="text-lg font-bold text-foreground">1. Acceptance of Terms</h2>
            <p className="mt-2">
              By accessing or using BeOnPoint (the "Service"), you agree to be bound
              by these Terms of Service. If you do not agree, do not use the Service.
              BeOnPoint is operated as a community-build application and is provided
              free of charge unless explicitly stated otherwise on a paid tier.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">2. Description of Service</h2>
            <p className="mt-2">
              BeOnPoint provides an AI-powered fashion styling experience, including
              virtual try-on analysis, persona-driven style critiques, shareable style
              polaroids, and a self-serve storefront system for curators and merchants.
              The Service integrates with third-party providers for wallet connectivity,
              payment processing, and identity verification.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">3. Account Registration</h2>
            <p className="mt-2">
              You may sign in via email and password or by linking a Web3 wallet. You
              are responsible for maintaining the security of your account and any
              connected wallet. BeOnPoint cannot recover funds lost due to compromised
              credentials or unauthorized wallet access.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">4. AI-Generated Content</h2>
            <p className="mt-2">
              Style critiques, scores, and recommendations are generated by artificial
              intelligence and are intended as entertainment and self-expression aids.
              They are not professional fashion, medical, or psychological advice. You
              remain solely responsible for outfit choices and purchases.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">5. User Content</h2>
            <p className="mt-2">
              You retain ownership of photos, storefront content, and other materials
              you upload. By uploading, you grant BeOnPoint a non-exclusive licence to
              process that content for the purpose of operating the Service (for
              example, running the AI styling pipeline or displaying your storefront).
            </p>
            <p className="mt-3">
              Uploaded try-on photos are processed in memory and are not persistently
              stored on BeOnPoint servers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">6. Curators and Storefronts</h2>
            <p className="mt-2">
              Curators are responsible for the accuracy of their storefront listings,
              pricing, contact information, and order fulfilment. BeOnPoint is not a
              party to transactions between curators and customers. Checkout happens
              off-platform (typically via WhatsApp or M-Pesa), and we do not process
              or guarantee those payments.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">7. Wallet and Blockchain Features</h2>
            <p className="mt-2">
              Where the Service connects to a Web3 wallet (for example to claim daily
              GoodDollar UBI on Celo), transactions are recorded on public blockchains.
              These transactions are irreversible. BeOnPoint is not responsible for
              network fees, smart-contract behaviour, or loss of funds due to user
              error.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">8. Subscriptions and Payments</h2>
            <p className="mt-2">
              Paid tiers (Plus, Pro, Concierge) are billed monthly or annually as
              described on the Pricing page. You may cancel at any time; cancellation
              stops future renewals but does not refund the current period unless
              required by law. Premium features are available on a 14-day free trial
              for new accounts.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">9. Prohibited Use</h2>
            <p className="mt-2">
              You agree not to use the Service to harass others, distribute illegal
              content, attempt to bypass rate limits or abuse free credits, scrape
              the platform, or interfere with its operation. We may suspend or
              terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">10. Disclaimer of Warranties</h2>
            <p className="mt-2">
              The Service is provided "as is" and "as available" without warranties
              of any kind, express or implied. We do not warrant that the Service
              will be uninterrupted, error-free, or that AI-generated outputs will
              meet your expectations.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">11. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, BeOnPoint and its contributors
              are not liable for any indirect, incidental, special, or consequential
              damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">12. Changes to Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. Material changes will be
              announced on the home page. Continued use of the Service after changes
              take effect constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground">13. Contact</h2>
            <p className="mt-2">
              For questions about these Terms, please reach out via the contact
              information available on our About page.
            </p>
          </section>
        </div>
      </article>

      <footer className="border-t border-border py-8">
        <div className="mx-auto flex max-w-3xl flex-col items-center justify-between gap-4 px-4 text-sm text-muted-foreground md:flex-row">
          <div className="flex items-center gap-2">
            <div className="rounded-lg bg-gradient-to-br from-primary to-accent p-1 shadow-md">
              <Palette className="h-3.5 w-3.5 text-white" />
            </div>
            BeOnPoint
          </div>
          <div className="flex items-center gap-4">
            <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
            <Link href="/about" className="hover:text-foreground transition-colors">About</Link>
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/guides" className="hover:text-foreground transition-colors">Guides</Link>
          </div>
          <p className="text-xs">Your privacy matters.</p>
        </div>
      </footer>
    </main>
  );
}
